version: '3'
services:
  fastapi:
    container_name: fastapi
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - kafka
      - zookeeper
    networks:
      - fastapi_network


  kafka:
    image: bitnami/kafka:3.2.3
    container_name: kafka
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_HOST_NAME: kafka
      KAFKA_CLIENT_USERS: kafka_user
      KAFKA_INTER_BROKER_USER: kafka_user
      KAFKA_INTER_BROKER_PASSWORD: kafka_user_pass
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
#    volumes:
#      - ./kafka_data:/bitnami/
#      - ./kafka_log:/tmp/kafka_mounts/logs
    networks:
      - fastapi_network

  zookeeper:
    image: bitnami/zookeeper:3.5.7
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - './zookeeper_data:/bitnami'
    ports:
      - 2181:2181
    expose:
      - 9093
    networks:
      - fastapi_network

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:latest
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: random
      KAFKA_MANAGER_AUTH_ENABLED: 'true'
      KAFKA_MANAGER_USERNAME: username
      KAFKA_MANAGER_PASSWORD: password
    ports:
      - "9000:9000"
    networks:
      - fastapi_network
networks:
  fastapi_network:
    driver: bridge
